/* Delimiter changed to ; */
/* Connecting to localhost via MariaDB or MySQL (TCP/IP), username root, using password: No ... */
SELECT CONNECTION_ID();
/* Connected. Thread-ID: 93 */
/* Characterset: utf8mb4 */
SHOW STATUS;
SELECT NOW();
SHOW VARIABLES;
SHOW DATABASES;
SHOW OPEN TABLES FROM pos WHERE `in_use`!=0;
USE `pos`;
/* Entering session "Laragon" */
SELECT `DEFAULT_COLLATION_NAME` FROM `information_schema`.`SCHEMATA` WHERE `SCHEMA_NAME`='pos';
SHOW TABLE STATUS FROM `pos`;
SHOW FUNCTION STATUS WHERE `Db`='pos';
SHOW PROCEDURE STATUS WHERE `Db`='pos';
SHOW TRIGGERS FROM `pos`;
SELECT `DEFAULT_COLLATION_NAME` FROM `information_schema`.`SCHEMATA` WHERE `SCHEMA_NAME`='information_schema';
SHOW TABLE STATUS FROM `information_schema`;
SHOW FUNCTION STATUS WHERE `Db`='information_schema';
SHOW PROCEDURE STATUS WHERE `Db`='information_schema';
SHOW TRIGGERS FROM `information_schema`;
SHOW EVENTS FROM `information_schema`;
SELECT *, EVENT_SCHEMA AS `Db`, EVENT_NAME AS `Name` FROM information_schema.`EVENTS` WHERE `EVENT_SCHEMA`='pos';
SHOW CREATE TABLE `pos`.`wp_wc_order_product_lookup`;
SHOW COLLATION;
SHOW ENGINES;
SHOW CREATE TABLE `pos`.`wp_wc_product_meta_lookup`;
SHOW CREATE TABLE `pos`.`wp_wc_product_download_directories`;
SHOW CREATE TABLE `pos`.`wp_wc_product_meta_lookup`;
SHOW CREATE TABLE `pos`.`wp_wc_product_attributes_lookup`;
SHOW CREATE TABLE `pos`.`wp_wc_product_download_directories`;
SHOW CREATE TABLE `pos`.`wp_wc_product_meta_lookup`;
SELECT * FROM `pos`.`wp_wc_product_meta_lookup` LIMIT 1000;
SHOW CREATE TABLE `pos`.`wp_wc_product_meta_lookup`;
SHOW CREATE TABLE `pos`.`wp_wc_product_download_directories`;
SELECT * FROM `pos`.`wp_wc_product_download_directories` LIMIT 1000;
SHOW CREATE TABLE `pos`.`wp_wc_product_download_directories`;
SHOW CREATE TABLE `pos`.`wp_wc_product_attributes_lookup`;
SELECT * FROM `pos`.`wp_wc_product_attributes_lookup` LIMIT 1000;
SHOW CREATE TABLE `pos`.`wp_wc_product_attributes_lookup`;
SHOW CREATE TABLE `pos`.`wp_wc_product_meta_lookup`;
SELECT * FROM `pos`.`wp_wc_product_meta_lookup` LIMIT 1000;
SHOW CREATE TABLE `pos`.`wp_wc_product_meta_lookup`;
SELECT * FROM `pos`.`wp_wc_product_meta_lookup` LIMIT 1000;
SHOW CREATE TABLE `pos`.`wp_wc_product_meta_lookup`;
SELECT * FROM `pos`.`wp_wc_product_meta_lookup` LIMIT 1000;
SHOW CREATE TABLE `pos`.`wp_wc_product_meta_lookup`;
SELECT * FROM `pos`.`wp_wc_product_meta_lookup` LIMIT 1000;
SHOW CREATE TABLE `pos`.`wp_wc_product_meta_lookup`;
SHOW CHARSET;
SELECT 'pos' AS `Database`, 'wp_actionscheduler_actions' AS `Table`, 94 AS `Rows`, 0 AS `Duration`;
/*!40101 SET @OLD_LOCAL_SQL_MODE=@@SQL_MODE, SQL_MODE='' */;
SELECT 'pos' AS `Database`, 'wp_actionscheduler_claims' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_actionscheduler_groups' AS `Table`, 3 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_actionscheduler_logs' AS `Table`, 274 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_commentmeta' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_comments' AS `Table`, 1 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_links' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_mailpoet_automations' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_mailpoet_automation_runs' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_mailpoet_automation_run_logs' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_mailpoet_automation_run_subjects' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_mailpoet_automation_triggers' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_mailpoet_automation_versions' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_mailpoet_custom_fields' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_mailpoet_dynamic_segment_filters' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_mailpoet_feature_flags' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_mailpoet_forms' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_mailpoet_log' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_mailpoet_migrations' AS `Table`, 13 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_mailpoet_newsletters' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_mailpoet_newsletter_links' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_mailpoet_newsletter_option' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_mailpoet_newsletter_option_fields' AS `Table`, 28 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_mailpoet_newsletter_posts' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_mailpoet_newsletter_segment' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_mailpoet_newsletter_templates' AS `Table`, 69 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_mailpoet_scheduled_tasks' AS `Table`, 15 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_mailpoet_scheduled_task_subscribers' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_mailpoet_segments' AS `Table`, 3 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_mailpoet_sending_queues' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_mailpoet_settings' AS `Table`, 14 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_mailpoet_statistics_bounces' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_mailpoet_statistics_clicks' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_mailpoet_statistics_forms' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_mailpoet_statistics_newsletters' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_mailpoet_statistics_opens' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_mailpoet_statistics_unsubscribes' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_mailpoet_statistics_woocommerce_purchases' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_mailpoet_stats_notifications' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_mailpoet_subscribers' AS `Table`, 1 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_mailpoet_subscriber_custom_field' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_mailpoet_subscriber_ips' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_mailpoet_subscriber_segment' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_mailpoet_subscriber_tag' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_mailpoet_tags' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_mailpoet_user_agents' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_mailpoet_user_flags' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_options' AS `Table`, 404 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_postmeta' AS `Table`, 174 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_posts' AS `Table`, 37 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_termmeta' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_terms' AS `Table`, 15 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_term_relationships' AS `Table`, 18 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_term_taxonomy' AS `Table`, 15 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_usermeta' AS `Table`, 27 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_users' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_wc_admin_notes' AS `Table`, 69 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_wc_admin_note_actions' AS `Table`, 96 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_wc_category_lookup' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_wc_customer_lookup' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_wc_download_log' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_wc_order_coupon_lookup' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_wc_order_product_lookup' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_wc_order_stats' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_wc_order_tax_lookup' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_wc_product_attributes_lookup' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_wc_product_download_directories' AS `Table`, 2 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_wc_product_meta_lookup' AS `Table`, 8 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_wc_rate_limits' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_wc_reserved_stock' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_wc_tax_rate_classes' AS `Table`, 2 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_wc_webhooks' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_woocommerce_api_keys' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_woocommerce_attribute_taxonomies' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_woocommerce_downloadable_product_permissions' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_woocommerce_log' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_woocommerce_order_itemmeta' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_woocommerce_order_items' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_woocommerce_payment_tokenmeta' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_woocommerce_payment_tokens' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_woocommerce_sessions' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_woocommerce_shipping_zones' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_woocommerce_shipping_zone_locations' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_woocommerce_shipping_zone_methods' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_woocommerce_tax_rates' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_woocommerce_tax_rate_locations' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
/*!40101 SET SQL_MODE=IFNULL(@OLD_LOCAL_SQL_MODE, '') */;
SELECT 'pos' AS `Database`, 'wp_actionscheduler_actions' AS `Table`, 94 AS `Rows`, 0 AS `Duration`;
/*!40101 SET @OLD_LOCAL_SQL_MODE=@@SQL_MODE, SQL_MODE='' */;
SELECT 'pos' AS `Database`, 'wp_actionscheduler_claims' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_actionscheduler_groups' AS `Table`, 3 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_actionscheduler_logs' AS `Table`, 274 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_commentmeta' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_comments' AS `Table`, 1 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_links' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_mailpoet_automations' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_mailpoet_automation_runs' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_mailpoet_automation_run_logs' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_mailpoet_automation_run_subjects' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_mailpoet_automation_triggers' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_mailpoet_automation_versions' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_mailpoet_custom_fields' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_mailpoet_dynamic_segment_filters' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_mailpoet_feature_flags' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_mailpoet_forms' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_mailpoet_log' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_mailpoet_migrations' AS `Table`, 13 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_mailpoet_newsletters' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_mailpoet_newsletter_links' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_mailpoet_newsletter_option' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_mailpoet_newsletter_option_fields' AS `Table`, 28 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_mailpoet_newsletter_posts' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_mailpoet_newsletter_segment' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_mailpoet_newsletter_templates' AS `Table`, 69 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_mailpoet_scheduled_tasks' AS `Table`, 15 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_mailpoet_scheduled_task_subscribers' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_mailpoet_segments' AS `Table`, 3 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_mailpoet_sending_queues' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_mailpoet_settings' AS `Table`, 14 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_mailpoet_statistics_bounces' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_mailpoet_statistics_clicks' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_mailpoet_statistics_forms' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_mailpoet_statistics_newsletters' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_mailpoet_statistics_opens' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_mailpoet_statistics_unsubscribes' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_mailpoet_statistics_woocommerce_purchases' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_mailpoet_stats_notifications' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_mailpoet_subscribers' AS `Table`, 1 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_mailpoet_subscriber_custom_field' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_mailpoet_subscriber_ips' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_mailpoet_subscriber_segment' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_mailpoet_subscriber_tag' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_mailpoet_tags' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_mailpoet_user_agents' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_mailpoet_user_flags' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_options' AS `Table`, 404 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_postmeta' AS `Table`, 174 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_posts' AS `Table`, 37 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_termmeta' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_terms' AS `Table`, 15 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_term_relationships' AS `Table`, 18 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_term_taxonomy' AS `Table`, 15 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_usermeta' AS `Table`, 27 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_users' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_wc_admin_notes' AS `Table`, 69 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_wc_admin_note_actions' AS `Table`, 96 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_wc_category_lookup' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_wc_customer_lookup' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_wc_download_log' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_wc_order_coupon_lookup' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_wc_order_product_lookup' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_wc_order_stats' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_wc_order_tax_lookup' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_wc_product_attributes_lookup' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_wc_product_download_directories' AS `Table`, 2 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_wc_product_meta_lookup' AS `Table`, 8 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_wc_rate_limits' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_wc_reserved_stock' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_wc_tax_rate_classes' AS `Table`, 2 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_wc_webhooks' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_woocommerce_api_keys' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_woocommerce_attribute_taxonomies' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_woocommerce_downloadable_product_permissions' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_woocommerce_log' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_woocommerce_order_itemmeta' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_woocommerce_order_items' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_woocommerce_payment_tokenmeta' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_woocommerce_payment_tokens' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_woocommerce_sessions' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_woocommerce_shipping_zones' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_woocommerce_shipping_zone_locations' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_woocommerce_shipping_zone_methods' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_woocommerce_tax_rates' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
SELECT 'pos' AS `Database`, 'wp_woocommerce_tax_rate_locations' AS `Table`, 0 AS `Rows`, 0 AS `Duration`;
/*!40101 SET SQL_MODE=IFNULL(@OLD_LOCAL_SQL_MODE, '') */;
SHOW CREATE TABLE `pos`.`wp_mailpoet_automation_runs`;